name: Release Build

on:
  release:
    types: [published, created]
  workflow_dispatch:
    inputs:
      tag_name:
        description: '发布的标签名称 (例如: v1.0.0)'
        required: true
        type: string

# 添加权限配置
permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      
      - name: Show Environment Info
        run: |
          java -version
          echo "Workspace directory:"
          dir
          echo "Gradle version:"
          ./gradlew --version
      
      - name: Build Windows Release
        run: |
          ./gradlew --no-daemon --info --stacktrace packageReleaseDistributionForCurrentOS
        env:
          GRADLE_OPTS: "-Xmx2g -XX:MaxMetaspaceSize=512m"
      
      - name: Find Build Artifacts
        run: |
          echo "Searching for build artifacts:"
          dir composeApp\build\compose\binaries /s /b | findstr ".msi$"
      
      - name: List Build Output
        run: |
          echo "Build output directory (desktop/app):"
          dir composeApp\build\compose\binaries\desktop\app\msi\ || echo "Directory not found"
          echo "Build output directory (main-release):"
          dir composeApp\build\compose\binaries\main-release\msi\ || echo "Directory not found"
      
      - name: Upload Windows Artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name || github.event.inputs.tag_name }}
          files: |
            composeApp/build/compose/binaries/main-release/msi/*.msi
  
  build-macos:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      
      - name: Show Environment Info
        run: |
          java -version
          echo "Workspace directory:"
          ls -la
          echo "Gradle version:"
          ./gradlew --version || true
      
      - name: Set Gradle Wrapper Permissions
        run: chmod +x ./gradlew
      
      - name: Build macOS Release
        run: ./gradlew packageReleaseDistributionForCurrentOS --no-daemon --info --stacktrace
      
      - name: Find Build Artifacts
        run: |
          echo "Searching for build artifacts:"
          find composeApp/build/compose/binaries -name "*.dmg" -type f
      
      - name: List Build Output
        run: |
          echo "Build output directory (desktop/app):"
          ls -la composeApp/build/compose/binaries/desktop/app/dmg/ || echo "Directory not found"
          echo "Build output directory (main-release):"
          ls -la composeApp/build/compose/binaries/main-release/dmg/ || echo "Directory not found"
      
      - name: Upload macOS Artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name || github.event.inputs.tag_name }}
          files: composeApp/build/compose/binaries/main-release/dmg/*.dmg
  
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      
      - name: Show Environment Info
        run: |
          java -version
          echo "Workspace directory:"
          ls -la
          echo "Gradle version:"
          ./gradlew --version || true
      
      - name: Set Gradle Wrapper Permissions
        run: chmod +x ./gradlew
      
      - name: Build Linux Release
        run: ./gradlew packageReleaseDistributionForCurrentOS --no-daemon --info --stacktrace
      
      - name: Find Build Artifacts
        run: |
          echo "Searching for build artifacts:"
          find composeApp/build/compose/binaries -name "*.deb" -type f
      
      - name: List Build Output
        run: |
          echo "Build output directory (desktop/app):"
          ls -la composeApp/build/compose/binaries/desktop/app/deb/ || echo "Directory not found"
          echo "Build output directory (main-release):"
          ls -la composeApp/build/compose/binaries/main-release/deb/ || echo "Directory not found"
      
      - name: Upload Linux Artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name || github.event.inputs.tag_name }}
          files: composeApp/build/compose/binaries/main-release/deb/*.deb 