name: Release Build

on:
  release:
    types: [published, created]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      
      - name: Show Environment Info
        run: |
          java -version
          echo "Workspace directory:"
          dir
          echo "Gradle version:"
          ./gradlew --version
      
      - name: Build Windows Release
        run: ./gradlew packageReleaseDistributionForCurrentOS --info --stacktrace
      
      - name: List Build Output
        run: |
          echo "Build output directory:"
          dir composeApp\build\compose\binaries\desktop\app\msi\
      
      - name: Upload Windows Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            composeApp/build/compose/binaries/desktop/app/msi/HugoGalleryUploader-*.msi
  
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      
      - name: Show Environment Info
        run: |
          java -version
          echo "Workspace directory:"
          ls -la
          echo "Gradle version:"
          ./gradlew --version || true
      
      - name: Set Gradle Wrapper Permissions
        run: chmod +x ./gradlew
      
      - name: Build macOS Release
        run: ./gradlew packageReleaseDistributionForCurrentOS --info --stacktrace
      
      - name: List Build Output
        run: |
          echo "Build output directory:"
          ls -la composeApp/build/compose/binaries/desktop/app/dmg/
      
      - name: Upload macOS Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            composeApp/build/compose/binaries/desktop/app/dmg/HugoGalleryUploader-*.dmg
  
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      
      - name: Show Environment Info
        run: |
          java -version
          echo "Workspace directory:"
          ls -la
          echo "Gradle version:"
          ./gradlew --version || true
      
      - name: Set Gradle Wrapper Permissions
        run: chmod +x ./gradlew
      
      - name: Build Linux Release
        run: ./gradlew packageReleaseDistributionForCurrentOS --info --stacktrace
      
      - name: List Build Output
        run: |
          echo "Build output directory:"
          ls -la composeApp/build/compose/binaries/desktop/app/deb/
      
      - name: Upload Linux Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            composeApp/build/compose/binaries/desktop/app/deb/hugoGalleryUploader_*.deb 