name: Release Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      
      - name: Build Windows Release
        run: ./gradlew packageReleaseDistributionForCurrentOS
      
      - name: Upload Windows Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            composeApp/build/compose/binaries/desktop/app/msi/HugoGalleryUploader-*.msi
  
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      
      - name: Build macOS Release
        run: ./gradlew packageReleaseDistributionForCurrentOS
      
      - name: Upload macOS Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            composeApp/build/compose/binaries/desktop/app/dmg/HugoGalleryUploader-*.dmg
  
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      
      - name: Build Linux Release
        run: ./gradlew packageReleaseDistributionForCurrentOS
      
      - name: Upload Linux Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            composeApp/build/compose/binaries/desktop/app/deb/hugoGalleryUploader_*.deb 